"""empty message

Revision ID: b20b495ee84b
Revises: f136476fc48e
Create Date: 2017-10-25 17:42:45.110078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20b495ee84b'
down_revision = 'f136476fc48e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('constraint', 'favorites', ['user_id', 'warble_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('constraint', table_name='favorites')
    # ### end Alembic commands ###
