"""empty message

Revision ID: f136476fc48e
Revises: 19e32bbdaff1
Create Date: 2017-10-25 17:37:32.036865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f136476fc48e'
down_revision = '19e32bbdaff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('constraint', 'favorites', ['user_id', 'warble_id'], unique=True)
    op.add_column('followers', sa.Column('follower_id', sa.Integer(), nullable=True))
    op.drop_constraint('followers_follow_id_fkey', 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'users', ['follower_id'], ['id'], ondelete='cascade')
    op.drop_column('followers', 'follow_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('follow_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key('followers_follow_id_fkey', 'followers', 'users', ['follow_id'], ['id'], ondelete='CASCADE')
    op.drop_column('followers', 'follower_id')
    op.drop_index('constraint', table_name='favorites')
    # ### end Alembic commands ###
